extends: airbnb-base
env:
  mocha: true
rules:
  array-bracket-spacing: [ error, always, { objectsInArrays: false } ]
  arrow-parens: [ error, always ]
  brace-style: [ error, stroustrup ]
  comma-dangle: [ error, never ]
  object-curly-spacing: [ error, always ]
  object-curly-newline: [ error, { multiline: true } ]
  no-underscore-dangle: [ off ]
  no-only-tests/no-only-tests: [ error ]
plugins: [ no-only-tests ]
